/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class groceryCount {

    public int count;

    private int overflows;

    public groceryCount() {
        count = 0;
    }

    public String total() {
        int tens = (count / 1000) % 10000;
        int temp = count % 1000;
        int ones = (temp / 100) % 1000;
        int temp2 = temp % 100;
        int tenths = (temp % 100) / 10;
        int temp3 = temp2 % 10;
        int hundreths = temp3 % 10;
        if (tens == 0) {
            return "$" + ones + "." + tenths + hundreths;
        }
        return "$" + tens + ones + "." + tenths + hundreths;
    }

    public void hundreths() {
        if (count == 9999) {
            count = 0;
            overflows++;
            count--;
        }
        count += 1;
    }

    public void tenths() {
        for (int i = 0; i < 10; i++) {
            if (count == 9999) {
                count = 0;
                overflows++;
                count--;
            }
            count++;
        }
    }

    public void ones() {
        for (int i = 0; i < 100; i++) {
            if (count == 9999) {
                count = 0;
                overflows++;
                count--;
            }
            count++;
        }
    }

    public void tens() {
        for (int i = 0; i < 1000; i++) {
            if (count == 9999) {
                count = 0;
                overflows++;
                count--;
            }
            count++;
        }
    }

    public int overflows() {
        if (count > 9999) {
            count = 0;
            overflows++;
        }
        return overflows;
    }

    public void clear() {
        count = 0;
    }



  // This is a sample main function just to show you how everything works
  // You can update it with a driver program for your solution
  public static void main(String[] args) {
    groceryCount counter = new groceryCount();
 
System.out.println(counter.total()); // This would print out $0.00
 
counter.tens();
counter.tens();
counter.hundreths();
 
System.out.println(counter.total()); // This would print out $20.01
System.out.println(counter.overflows()); // This would print out 0
 
for(int i = 0; i < 35; i++) {
  counter.ones();
}
 
System.out.println(counter.total()); // This would print out $55.01
System.out.println(counter.overflows()); // This would print out 0
 
for(int i = 0; i < 4000; i++) {
  counter.tenths();
}
 
System.out.println(counter.total()); // This would print out $55.01
System.out.println(counter.overflows()); // This would print out 1
 
counter.clear();
 
System.out.println(counter.total()); // This would print out $0.00
System.out.println(counter.overflows()); // This would print out 0
  }

}
